### ISSUE TITLE
Posterior mean LOESS line issues, might be my data

### ISSUE THREAD

**Issue by anmwinter** [rasmusab/bayesboot#6]
Hi, 

 I was playing around with the loess bayesboot with some of my data. For a few categories I get what looks like some strange posterior mean LOESS lines. This may be a function of my data or misuse of the loess for data like this. 

![bayesboot_chloroflexi](https://cloud.githubusercontent.com/assets/2340132/20198840/21ca18b2-a764-11e6-8da8-c9c12d6634a8.png)

I've attached my data that is read into R as well.
[batesboot_bat_data.txt](https://github.com/rasmusab/bayesboot/files/584682/batesboot_bat_data.txt)

**Comment by rasmusab** [comment]
Could you please supply the code you used to create this graph?

**Comment by anmwinter** [comment]
Sorry! Here it is.

library(bayesboot)
boot_majors <- read.csv("batesboot_bat_data.txt",sep="\t")
head(boot_majors)

boot_fn <- function(boot_majors, weights) {
  loess(Actinobacteria ~ lat, boot_majors, weights = weights)$fitted
}

bb_loess <- bayesboot(boot_majors, boot_fn, use.weights = TRUE)

plot(boot_majors$lat, boot_majors$Actinobacteria, pch = 20, col = "tomato4", xlab = "Lat", 
     ylab = "Counts - Firmicutes", main = "OTU Counts and Latitude of Sampling Site")

for(i in sample(nrow(bb_loess), 20)) {
  lines(boot_majors$lat, bb_loess[i,], col = "gray")
}

lines(boot_majors$lat, colMeans(bb_loess, na.rm = TRUE), type ="l",
      col = "tomato", lwd = 1)

**Comment by rasmusab** [comment]
Try the following instead:

```
library(bayesboot)
boot_majors <- read.csv("batesboot_bat_data.txt",sep="\t")
head(boot_majors)

lat_pred = seq(30, 40, 0.1)
boot_fn <- function(boot_majors, weights) {
  predict(loess(Actinobacteria ~ lat, boot_majors, weights = weights), 
          data.frame(lat = lat_pred))
}

bb_loess <- bayesboot(boot_majors, boot_fn, use.weights = TRUE)

plot(boot_majors$lat, boot_majors$Actinobacteria, pch = 20, col = "tomato4", xlab = "Lat",
     ylab = "Counts - Firmicutes", main = "OTU Counts and Latitude of Sampling Site")

for(i in sample(nrow(bb_loess), 20)) {
  lines(lat_pred, bb_loess[i,], col = "gray")
}

lines(lat_pred, colMeans(bb_loess, na.rm = TRUE), type ="l",
      col = "tomato", lwd = 3)

```

**Comment by anmwinter** [comment]
Thank you very much! I am trying to sort out what the seq did that made the plot come out nice.
